# Generated from rpg_skill_system_simulation_cleaned.xlsx.
from __future__ import annotations

import re

SKILLS = [
    {
        "id": 1,
        "type": "近戰",
        "school": "戰士流",
        "name": "迅斬",
        "rarity": "普通",
        "multiplier": 1,
        "cooldown": 0,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "造成 ATK×100% 傷害。沒有額外效果，作為無冷卻填充技能。",
        "note": None
    },
    {
        "id": 2,
        "type": "近戰",
        "school": "戰士流",
        "name": "重斬",
        "rarity": "普通",
        "multiplier": 1.2,
        "cooldown": 1,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "造成 ATK×120% 傷害。適合冷卻短的穩定輸出。",
        "note": None
    },
    {
        "id": 3,
        "type": "近戰",
        "school": "戰士流",
        "name": "盾擊",
        "rarity": "普通",
        "multiplier": 1,
        "cooldown": 1,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "造成 ATK×100% 傷害，並使敵人 ATK -10%，持續 2 回合。",
        "note": None
    },
    {
        "id": 4,
        "type": "近戰",
        "school": "戰士流",
        "name": "破甲斬",
        "rarity": "稀有",
        "multiplier": 1.5,
        "cooldown": 2,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "造成 ATK×150% 傷害，並使敵人 DEF -15%，持續 3 回合。",
        "note": None
    },
    {
        "id": 5,
        "type": "近戰",
        "school": "戰士流",
        "name": "血刃",
        "rarity": "稀有",
        "multiplier": 1.55,
        "cooldown": 2,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "造成 ATK×155% 傷害，並回復本次造成傷害的 10% HP。",
        "note": None
    },
    {
        "id": 6,
        "type": "近戰",
        "school": "戰士流",
        "name": "裂地斬",
        "rarity": "史詩",
        "multiplier": 2.05,
        "cooldown": 3,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "造成 ATK×205% 傷害，並使敵人 SPD -20%，持續 2 回合。",
        "note": None
    },
    {
        "id": 7,
        "type": "近戰",
        "school": "戰士流",
        "name": "戰神連斬",
        "rarity": "史詩",
        "multiplier": 2.3,
        "cooldown": 3,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "造成 ATK×230% 傷害。純爆發技能。",
        "note": None
    },
    {
        "id": 8,
        "type": "近戰",
        "school": "戰士流",
        "name": "聖裁斬",
        "rarity": "傳說",
        "multiplier": 2.9,
        "cooldown": 4,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "造成 ATK×290% 傷害；若敵人是不死、惡魔、黑暗類，傷害額外 +25%。",
        "note": None
    },
    {
        "id": 9,
        "type": "近戰",
        "school": "戰士流",
        "name": "王權處刑",
        "rarity": "傳說",
        "multiplier": 3,
        "cooldown": 4,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "造成 ATK×300% 傷害；敵人 HP 低於 35% 時，倍率改為 390%。",
        "note": None
    },
    {
        "id": 10,
        "type": "近戰",
        "school": "戰士流",
        "name": "修羅百裂",
        "rarity": "神話",
        "multiplier": 4.2,
        "cooldown": 6,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "造成 ATK×420% 傷害；若擊敗敵人，所有近戰技能冷卻 -1 回合。",
        "note": None
    },
    {
        "id": 11,
        "type": "近戰",
        "school": "自殘狂戰流",
        "name": "血契斬",
        "rarity": "稀有",
        "multiplier": 1.65,
        "cooldown": 2,
        "self_hp_cost": "6%",
        "sword_aura": None,
        "effect": "消耗自身最大 HP 6%，造成 ATK×165% 傷害，並追加 ATK×40% 傷害。",
        "note": None
    },
    {
        "id": 12,
        "type": "近戰",
        "school": "自殘狂戰流",
        "name": "裂血突擊",
        "rarity": "史詩",
        "multiplier": 2.15,
        "cooldown": 3,
        "self_hp_cost": "8%",
        "sword_aura": None,
        "effect": "消耗自身最大 HP 8%，造成 ATK×215% 傷害，並附加流血：每回合 ATK×25% 傷害，持續 3 回合。",
        "note": None
    },
    {
        "id": 13,
        "type": "近戰",
        "school": "自殘狂戰流",
        "name": "狂骨斷斬",
        "rarity": "史詩",
        "multiplier": 2.25,
        "cooldown": 3,
        "self_hp_cost": "8%",
        "sword_aura": None,
        "effect": "消耗自身最大 HP 8%，造成 ATK×225% 傷害，並使敵人 DEF -20%，持續 2 回合。",
        "note": None
    },
    {
        "id": 14,
        "type": "近戰",
        "school": "自殘狂戰流",
        "name": "血怒終斬",
        "rarity": "傳說",
        "multiplier": 3.1,
        "cooldown": 4,
        "self_hp_cost": "10%",
        "sword_aura": None,
        "effect": "消耗自身最大 HP 10%，造成 ATK×310% 傷害；自身 HP 低於 50% 時，倍率改為 420%。",
        "note": None
    },
    {
        "id": 15,
        "type": "近戰",
        "school": "自殘狂戰流",
        "name": "猩紅裁決",
        "rarity": "神話",
        "multiplier": 4.3,
        "cooldown": 6,
        "self_hp_cost": "12%",
        "sword_aura": None,
        "effect": "消耗自身最大 HP 12%，造成 ATK×430% 傷害；自身 HP 越低倍率越高，最多額外 +160% 倍率。",
        "note": None
    },
    {
        "id": 16,
        "type": "近戰",
        "school": "刺殺流",
        "name": "影步刺",
        "rarity": "普通",
        "multiplier": 0.95,
        "cooldown": 0,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "造成 ATK×95% 傷害，額外根據 SPD 增傷：min(SPD×0.2%, 60%)。",
        "note": None
    },
    {
        "id": 17,
        "type": "近戰",
        "school": "刺殺流",
        "name": "背襲",
        "rarity": "普通",
        "multiplier": 1.1,
        "cooldown": 1,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "造成 ATK×110% 傷害；若自身 SPD 高於敵人，額外 +25% 倍率。",
        "note": None
    },
    {
        "id": 18,
        "type": "近戰",
        "school": "刺殺流",
        "name": "疾影連刺",
        "rarity": "稀有",
        "multiplier": 1.35,
        "cooldown": 2,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "造成 ATK×135% 傷害，額外根據 SPD 增傷；自身 SPD +10%，持續 2 回合。",
        "note": None
    },
    {
        "id": 19,
        "type": "近戰",
        "school": "刺殺流",
        "name": "影痕刻印",
        "rarity": "稀有",
        "multiplier": 1.25,
        "cooldown": 2,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "造成 ATK×125% 傷害，給敵人 1 層影痕，最多 3 層，持續 4 回合。",
        "note": None
    },
    {
        "id": 20,
        "type": "近戰",
        "school": "刺殺流",
        "name": "無聲割喉",
        "rarity": "史詩",
        "multiplier": 1.7,
        "cooldown": 3,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "造成 ATK×170% 傷害；消耗所有影痕，每層影痕額外 +45% 倍率。",
        "note": None
    },
    {
        "id": 21,
        "type": "近戰",
        "school": "刺殺流",
        "name": "夜幕追擊",
        "rarity": "史詩",
        "multiplier": 1.85,
        "cooldown": 3,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "造成 ATK×185% 傷害；若自身有 SPD Buff，額外 +70% 倍率。",
        "note": None
    },
    {
        "id": 22,
        "type": "近戰",
        "school": "刺殺流",
        "name": "斷喉處刑",
        "rarity": "傳說",
        "multiplier": 2.45,
        "cooldown": 4,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "造成 ATK×245% 傷害；敵人 HP 低於 40% 時，額外 +150% 倍率。",
        "note": None
    },
    {
        "id": 23,
        "type": "近戰",
        "school": "刺殺流",
        "name": "無月刺殺",
        "rarity": "神話",
        "multiplier": 3.4,
        "cooldown": 6,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "造成 ATK×340% 傷害，額外根據 SPD 增傷；消耗影痕，每層額外 +60% 倍率。",
        "note": None
    },
    {
        "id": 24,
        "type": "近戰",
        "school": "武士劍氣流",
        "name": "居合斬",
        "rarity": "普通",
        "multiplier": 1.05,
        "cooldown": 1,
        "self_hp_cost": None,
        "sword_aura": "+1",
        "effect": "造成 ATK×105% 傷害，獲得 1 層劍氣。",
        "note": None
    },
    {
        "id": 25,
        "type": "近戰",
        "school": "武士劍氣流",
        "name": "逆袈裟斬",
        "rarity": "稀有",
        "multiplier": 1.45,
        "cooldown": 2,
        "self_hp_cost": None,
        "sword_aura": "+1",
        "effect": "造成 ATK×145% 傷害，獲得 1 層劍氣；敵人 DEF -10%，持續 2 回合。",
        "note": None
    },
    {
        "id": 26,
        "type": "近戰",
        "school": "武士劍氣流",
        "name": "拔刀返",
        "rarity": "稀有",
        "multiplier": 1.3,
        "cooldown": 2,
        "self_hp_cost": None,
        "sword_aura": "+1",
        "effect": "造成 ATK×130% 傷害，獲得 1 層劍氣；若上一回合受到傷害，額外 +50% 倍率。",
        "note": None
    },
    {
        "id": 27,
        "type": "近戰",
        "school": "武士劍氣流",
        "name": "一文字",
        "rarity": "史詩",
        "multiplier": 2,
        "cooldown": 3,
        "self_hp_cost": None,
        "sword_aura": "+2",
        "effect": "造成 ATK×200% 傷害，獲得 2 層劍氣。",
        "note": None
    },
    {
        "id": 28,
        "type": "近戰",
        "school": "武士劍氣流",
        "name": "劍氣解放",
        "rarity": "史詩",
        "multiplier": 1.8,
        "cooldown": 3,
        "self_hp_cost": None,
        "sword_aura": "-1",
        "effect": "消耗 1 層劍氣。最終倍率 = 180% + 175%×消耗劍氣層數。",
        "note": None
    },
    {
        "id": 29,
        "type": "近戰",
        "school": "武士劍氣流",
        "name": "霞斬",
        "rarity": "傳說",
        "multiplier": 2.7,
        "cooldown": 4,
        "self_hp_cost": None,
        "sword_aura": "-2",
        "effect": "消耗 2 層劍氣。最終倍率 = 270% + 175%×消耗劍氣層數。",
        "note": None
    },
    {
        "id": 30,
        "type": "近戰",
        "school": "武士劍氣流",
        "name": "無明三段",
        "rarity": "傳說",
        "multiplier": 2.4,
        "cooldown": 4,
        "self_hp_cost": None,
        "sword_aura": "+1",
        "effect": "造成 ATK×240% 傷害，獲得 1 層劍氣；視為三段攻擊，適合搭配暴擊效果。",
        "note": None
    },
    {
        "id": 31,
        "type": "近戰",
        "school": "武士劍氣流",
        "name": "天照一閃",
        "rarity": "神話",
        "multiplier": 3,
        "cooldown": 7,
        "self_hp_cost": None,
        "sword_aura": "全消耗",
        "effect": "消耗全部劍氣。最終倍率 = 300% + 175%×消耗劍氣層數；建議不可暴擊。",
        "note": None
    },
    {
        "id": 32,
        "type": "遠程",
        "school": "基礎射手流",
        "name": "快射",
        "rarity": "普通",
        "multiplier": 1,
        "cooldown": 0,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "造成 RATK×100% 傷害。",
        "note": None
    },
    {
        "id": 33,
        "type": "遠程",
        "school": "基礎射手流",
        "name": "精準射擊",
        "rarity": "普通",
        "multiplier": 1.2,
        "cooldown": 0,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "造成 RATK×120% 傷害；自身暴擊率 +8%，持續 1 回合。",
        "note": None
    },
    {
        "id": 34,
        "type": "遠程",
        "school": "基礎射手流",
        "name": "穿刺射擊",
        "rarity": "普通",
        "multiplier": 1.3,
        "cooldown": 1,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "造成 RATK×130% 傷害；無視敵人 5% DEF。",
        "note": None
    },
    {
        "id": 35,
        "type": "遠程",
        "school": "基礎射手流",
        "name": "爆裂箭",
        "rarity": "稀有",
        "multiplier": 1.55,
        "cooldown": 2,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "對全體敵人造成 RATK×155% 傷害。",
        "note": None
    },
    {
        "id": 36,
        "type": "遠程",
        "school": "基礎射手流",
        "name": "三連射",
        "rarity": "稀有",
        "multiplier": 1.7,
        "cooldown": 2,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "造成 RATK×170% 傷害。",
        "note": None
    },
    {
        "id": 37,
        "type": "遠程",
        "school": "基礎射手流",
        "name": "狙擊",
        "rarity": "稀有",
        "multiplier": 1.8,
        "cooldown": 2,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "造成 RATK×180% 傷害；本次暴擊傷害 +30%。",
        "note": None
    },
    {
        "id": 38,
        "type": "遠程",
        "school": "基礎射手流",
        "name": "風暴箭雨",
        "rarity": "史詩",
        "multiplier": 2.3,
        "cooldown": 3,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "對全體敵人造成 RATK×230% 傷害。",
        "note": None
    },
    {
        "id": 39,
        "type": "遠程",
        "school": "基礎射手流",
        "name": "影縫射擊",
        "rarity": "史詩",
        "multiplier": 2.1,
        "cooldown": 3,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "造成 RATK×210% 傷害；敵人無法獲得新的 Buff，持續 2 回合。",
        "note": None
    },
    {
        "id": 40,
        "type": "遠程",
        "school": "基礎射手流",
        "name": "彈幕封鎖",
        "rarity": "傳說",
        "multiplier": 3,
        "cooldown": 4,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "對全體敵人造成 RATK×300% 傷害；敵人 ATK -15%，持續 2 回合。",
        "note": None
    },
    {
        "id": 41,
        "type": "遠程",
        "school": "基礎射手流",
        "name": "星隕狙擊",
        "rarity": "神話",
        "multiplier": 4.3,
        "cooldown": 6,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "造成 RATK×430% 傷害；本次暴擊傷害 +70%；使用後自身 SPD -20%，持續 1 回合。",
        "note": None
    },
    {
        "id": 42,
        "type": "遠程",
        "school": "自殘射擊流",
        "name": "血羽箭",
        "rarity": "稀有",
        "multiplier": 1.65,
        "cooldown": 2,
        "self_hp_cost": "3%",
        "sword_aura": None,
        "effect": "消耗自身最大 HP 3%，造成 RATK×165% 傷害，並追加 RATK×25% 傷害。",
        "note": None
    },
    {
        "id": 43,
        "type": "遠程",
        "school": "自殘射擊流",
        "name": "赤弦連射",
        "rarity": "史詩",
        "multiplier": 2.2,
        "cooldown": 3,
        "self_hp_cost": "4%",
        "sword_aura": None,
        "effect": "消耗自身最大 HP 4%，造成 RATK×220% 傷害，並附加流血：每回合 RATK×20% 傷害，持續 3 回合。",
        "note": None
    },
    {
        "id": 44,
        "type": "遠程",
        "school": "自殘射擊流",
        "name": "禁弩過載",
        "rarity": "史詩",
        "multiplier": 2.35,
        "cooldown": 3,
        "self_hp_cost": "5%",
        "sword_aura": None,
        "effect": "消耗自身最大 HP 5%，造成 RATK×235% 傷害；下一個遠程技能傷害 +20%。",
        "note": None
    },
    {
        "id": 45,
        "type": "遠程",
        "school": "自殘射擊流",
        "name": "祭血狙殺",
        "rarity": "傳說",
        "multiplier": 3.2,
        "cooldown": 4,
        "self_hp_cost": "6%",
        "sword_aura": None,
        "effect": "消耗自身最大 HP 6%，造成 RATK×320% 傷害；若敵人有標記，額外 +70% 倍率；HP 低於 50% 時倍率改為 390%。",
        "note": None
    },
    {
        "id": 46,
        "type": "遠程",
        "school": "自殘射擊流",
        "name": "血月終弩",
        "rarity": "神話",
        "multiplier": 4.1,
        "cooldown": 6,
        "self_hp_cost": "7%",
        "sword_aura": None,
        "effect": "消耗自身最大 HP 7%，造成 RATK×410% 傷害；下一回合自動追加 RATK×80% 傷害；HP 越低最高額外 +110% 倍率。",
        "note": None
    },
    {
        "id": 47,
        "type": "遠程",
        "school": "破甲流",
        "name": "裂甲箭",
        "rarity": "普通",
        "multiplier": 1.25,
        "cooldown": 1,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "造成 RATK×125% 傷害，給敵人 1 層裂甲。裂甲：DEF -8%，最多 3 層，持續 4 回合。",
        "note": None
    },
    {
        "id": 48,
        "type": "遠程",
        "school": "破甲流",
        "name": "破盾釘射",
        "rarity": "稀有",
        "multiplier": 1.6,
        "cooldown": 2,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "造成 RATK×160% 傷害；若敵人有護盾，削減 30% 護盾值。",
        "note": None
    },
    {
        "id": 49,
        "type": "遠程",
        "school": "破甲流",
        "name": "剝甲連弩",
        "rarity": "史詩",
        "multiplier": 2.1,
        "cooldown": 3,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "造成 RATK×210% 傷害，給敵人 2 層裂甲。",
        "note": None
    },
    {
        "id": 50,
        "type": "遠程",
        "school": "破甲流",
        "name": "鐵雨壓制",
        "rarity": "史詩",
        "multiplier": 2.2,
        "cooldown": 3,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "對全體敵人造成 RATK×220% 傷害，並給 1 層裂甲。",
        "note": None
    },
    {
        "id": 51,
        "type": "遠程",
        "school": "破甲流",
        "name": "穿城巨弩",
        "rarity": "傳說",
        "multiplier": 3.3,
        "cooldown": 4,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "造成 RATK×330% 傷害；敵人每有 1 層裂甲，額外 +40% 倍率。",
        "note": None
    },
    {
        "id": 52,
        "type": "遠程",
        "school": "破甲流",
        "name": "破界弩砲",
        "rarity": "神話",
        "multiplier": 4.5,
        "cooldown": 6,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "造成 RATK×450% 傷害；無視敵人 30% DEF；敵人每有 1 層裂甲，額外 +60% 倍率。",
        "note": None
    },
    {
        "id": 53,
        "type": "遠程",
        "school": "最大生命值流",
        "name": "獵巨箭",
        "rarity": "稀有",
        "multiplier": 1.5,
        "cooldown": 2,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "造成 RATK×150% 傷害，額外造成目標最大 HP 1.5% 傷害；Boss 額外傷害上限 = RATK×60%。",
        "note": None
    },
    {
        "id": 54,
        "type": "遠程",
        "school": "最大生命值流",
        "name": "裂心射擊",
        "rarity": "史詩",
        "multiplier": 2.05,
        "cooldown": 3,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "造成 RATK×205% 傷害，額外造成目標最大 HP 2.5% 傷害；Boss 額外傷害上限 = RATK×100%。",
        "note": None
    },
    {
        "id": 55,
        "type": "遠程",
        "school": "最大生命值流",
        "name": "巨獸縛矢",
        "rarity": "史詩",
        "multiplier": 1.95,
        "cooldown": 3,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "造成 RATK×195% 傷害，額外造成目標最大 HP 2% 傷害，並給予巨獸標記 4 回合。",
        "note": None
    },
    {
        "id": 56,
        "type": "遠程",
        "school": "最大生命值流",
        "name": "屠龍穿心",
        "rarity": "傳說",
        "multiplier": 3,
        "cooldown": 4,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "造成 RATK×300% 傷害，額外造成目標最大 HP 4% 傷害；Boss 額外傷害上限 = RATK×180%。",
        "note": None
    },
    {
        "id": 57,
        "type": "遠程",
        "school": "最大生命值流",
        "name": "終末獵星",
        "rarity": "神話",
        "multiplier": 3.9,
        "cooldown": 6,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "造成 RATK×390% 傷害，額外造成目標最大 HP 8% 傷害；若有巨獸標記，改為 10%；Boss 額外傷害上限 = RATK×350%。",
        "note": None
    },
    {
        "id": 58,
        "type": "遠程",
        "school": "標記延遲流",
        "name": "追獵信標",
        "rarity": "稀有",
        "multiplier": 1.45,
        "cooldown": 2,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "造成 RATK×145% 傷害；敵人受到遠程傷害 +15%，持續 4 回合。",
        "note": None
    },
    {
        "id": 59,
        "type": "遠程",
        "school": "標記延遲流",
        "name": "迴音箭",
        "rarity": "稀有",
        "multiplier": 1.6,
        "cooldown": 2,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "造成 RATK×160% 傷害；下一回合自動追加 RATK×70% 傷害。",
        "note": None
    },
    {
        "id": 60,
        "type": "遠程",
        "school": "標記延遲流",
        "name": "死線預告",
        "rarity": "史詩",
        "multiplier": 2,
        "cooldown": 3,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "造成 RATK×200% 傷害；2 回合後追加 RATK×120% 傷害。",
        "note": None
    },
    {
        "id": 61,
        "type": "遠程",
        "school": "標記延遲流",
        "name": "月蝕狙殺",
        "rarity": "神話",
        "multiplier": 4.2,
        "cooldown": 6,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "造成 RATK×420% 傷害；若敵人有標記或裂甲，倍率改為 520%。",
        "note": None
    },
    {
        "id": 62,
        "type": "遠程",
        "school": "標記延遲流",
        "name": "日輪終矢",
        "rarity": "神話",
        "multiplier": 4.4,
        "cooldown": 6,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "造成 RATK×440% 傷害；若敵人身上有 3 個以上負面狀態，所有遠程技能冷卻 -1 回合。",
        "note": None
    },
    {
        "id": 63,
        "type": "魔法",
        "school": "元素Debuff流",
        "name": "魔彈",
        "rarity": "普通",
        "multiplier": 0.9,
        "cooldown": 0,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "造成 MATK×90% 傷害。",
        "note": None
    },
    {
        "id": 64,
        "type": "魔法",
        "school": "元素Debuff流",
        "name": "火球術",
        "rarity": "普通",
        "multiplier": 1.2,
        "cooldown": 0,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "造成 MATK×120% 傷害，附加燃燒：每回合 MATK×10% 傷害，持續 4 回合。",
        "note": None
    },
    {
        "id": 65,
        "type": "魔法",
        "school": "元素Debuff流",
        "name": "冰錐術",
        "rarity": "普通",
        "multiplier": 1.15,
        "cooldown": 1,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "造成 MATK×115% 傷害，敵人 SPD -10%，持續 4 回合。",
        "note": None
    },
    {
        "id": 66,
        "type": "魔法",
        "school": "元素Debuff流",
        "name": "雷擊",
        "rarity": "普通",
        "multiplier": 1.3,
        "cooldown": 1,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "造成 MATK×130% 傷害；本次暴擊率 +10%。",
        "note": None
    },
    {
        "id": 67,
        "type": "魔法",
        "school": "元素Debuff流",
        "name": "毒霧",
        "rarity": "稀有",
        "multiplier": 1.1,
        "cooldown": 2,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "對全體敵人造成 MATK×110% 傷害，附加中毒：每回合 MATK×15% 傷害，持續 4 回合。",
        "note": None
    },
    {
        "id": 68,
        "type": "魔法",
        "school": "元素Debuff流",
        "name": "炎爆術",
        "rarity": "稀有",
        "multiplier": 1.65,
        "cooldown": 2,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "造成 MATK×165% 傷害，附加燃燒：每回合 MATK×25% 傷害，持續 4 回合。",
        "note": None
    },
    {
        "id": 69,
        "type": "魔法",
        "school": "元素Debuff流",
        "name": "岩槍術",
        "rarity": "稀有",
        "multiplier": 1.7,
        "cooldown": 2,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "造成 MATK×170% 傷害，敵人 DEF -15%，持續 4 回合。",
        "note": None
    },
    {
        "id": 70,
        "type": "魔法",
        "school": "元素Debuff流",
        "name": "暗影球",
        "rarity": "稀有",
        "multiplier": 1.6,
        "cooldown": 2,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "造成 MATK×160% 傷害，並回復本次造成傷害的 8% HP。",
        "note": None
    },
    {
        "id": 71,
        "type": "魔法",
        "school": "元素Debuff流",
        "name": "流星雨",
        "rarity": "史詩",
        "multiplier": 2.3,
        "cooldown": 3,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "對全體敵人造成 MATK×230% 傷害。",
        "note": None
    },
    {
        "id": 72,
        "type": "魔法",
        "school": "元素Debuff流",
        "name": "深淵爆裂",
        "rarity": "史詩",
        "multiplier": 2.4,
        "cooldown": 3,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "造成 MATK×240% 傷害，敵人受到治療效果 -40%，持續 4 回合。",
        "note": None
    },
    {
        "id": 73,
        "type": "魔法",
        "school": "元素Debuff流",
        "name": "極寒末日",
        "rarity": "傳說",
        "multiplier": 3.1,
        "cooldown": 4,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "對全體敵人造成 MATK×310% 傷害，敵人 SPD -25%，持續 4 回合。",
        "note": None
    },
    {
        "id": 74,
        "type": "魔法",
        "school": "元素Debuff流",
        "name": "混沌星核",
        "rarity": "神話",
        "multiplier": 4.3,
        "cooldown": 6,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "造成 MATK×430% 傷害，隨機附加 2 種 Debuff，持續 4 回合。",
        "note": None
    },
    {
        "id": 75,
        "type": "魔法",
        "school": "控場流",
        "name": "寒冰牢籠",
        "rarity": "稀有",
        "multiplier": 1.45,
        "cooldown": 3,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "造成 MATK×145% 傷害；敵人下一回合不能行動，且 SPD -10%，持續 4 回合。",
        "note": None
    },
    {
        "id": 76,
        "type": "魔法",
        "school": "控場流",
        "name": "重力井",
        "rarity": "史詩",
        "multiplier": 2,
        "cooldown": 3,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "造成 MATK×200% 傷害；敵人 SPD -25%，且受到的下一次魔法傷害 +20%，持續 4 回合。",
        "note": None
    },
    {
        "id": 77,
        "type": "魔法",
        "school": "控場流",
        "name": "沉默符文",
        "rarity": "史詩",
        "multiplier": 1.9,
        "cooldown": 4,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "造成 MATK×190% 傷害；敵人不能使用 Buff 技能，持續 2 回合。",
        "note": None
    },
    {
        "id": 78,
        "type": "魔法",
        "school": "控場流",
        "name": "時間鎖",
        "rarity": "傳說",
        "multiplier": 2.8,
        "cooldown": 5,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "造成 MATK×280% 傷害；敵人所有技能冷卻 +1 回合，且 SPD -20%，持續 4 回合。",
        "note": None
    },
    {
        "id": 79,
        "type": "魔法",
        "school": "控場流",
        "name": "星界囚籠",
        "rarity": "神話",
        "multiplier": 3.6,
        "cooldown": 6,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "造成 MATK×360% 傷害；敵人下一回合不能行動，並延長敵人身上所有 Debuff 1 回合，最多延長到 5 回合。",
        "note": None
    },
    {
        "id": 80,
        "type": "魔法",
        "school": "暴擊傷害流",
        "name": "符文火花",
        "rarity": "普通",
        "multiplier": 1.05,
        "cooldown": 0,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "造成 MATK×105% 傷害；下一次魔法暴擊傷害 +10%，持續 2 回合。",
        "note": None
    },
    {
        "id": 81,
        "type": "魔法",
        "school": "暴擊傷害流",
        "name": "魔紋刻印",
        "rarity": "稀有",
        "multiplier": 1.4,
        "cooldown": 2,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "造成 MATK×140% 傷害；敵人受到的魔法暴擊傷害 +25%，持續 4 回合。",
        "note": None
    },
    {
        "id": 82,
        "type": "魔法",
        "school": "暴擊傷害流",
        "name": "晶核爆破",
        "rarity": "史詩",
        "multiplier": 2.1,
        "cooldown": 3,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "造成 MATK×210% 傷害；若本次暴擊，額外造成 MATK×80% 傷害。",
        "note": None
    },
    {
        "id": 83,
        "type": "魔法",
        "school": "暴擊傷害流",
        "name": "雙星共鳴",
        "rarity": "史詩",
        "multiplier": 1.9,
        "cooldown": 3,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "造成 MATK×190% 傷害；自身魔法暴擊傷害 +35%，持續 2 回合。",
        "note": None
    },
    {
        "id": 84,
        "type": "魔法",
        "school": "暴擊傷害流",
        "name": "災厄彗星",
        "rarity": "傳說",
        "multiplier": 3.2,
        "cooldown": 4,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "造成 MATK×320% 傷害；若敵人有魔紋刻印，額外 +80% 倍率。",
        "note": None
    },
    {
        "id": 85,
        "type": "魔法",
        "school": "暴擊傷害流",
        "name": "天啟星爆",
        "rarity": "神話",
        "multiplier": 4.1,
        "cooldown": 6,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "造成 MATK×410% 傷害；若本次暴擊，額外造成 MATK×180% 傷害。",
        "note": None
    },
    {
        "id": 86,
        "type": "魔法",
        "school": "自殘禁咒流",
        "name": "血咒火",
        "rarity": "稀有",
        "multiplier": 1.55,
        "cooldown": 2,
        "self_hp_cost": "2%",
        "sword_aura": None,
        "effect": "消耗自身最大 HP 2%，造成 MATK×155% 傷害，附加燃燒，持續 4 回合。",
        "note": None
    },
    {
        "id": 87,
        "type": "魔法",
        "school": "自殘禁咒流",
        "name": "禁書回響",
        "rarity": "史詩",
        "multiplier": 2.15,
        "cooldown": 3,
        "self_hp_cost": "3%",
        "sword_aura": None,
        "effect": "消耗自身最大 HP 3%，造成 MATK×215% 傷害；敵人每有 1 個 Debuff，額外 +20% 倍率，最多 +80%。",
        "note": None
    },
    {
        "id": 88,
        "type": "魔法",
        "school": "自殘禁咒流",
        "name": "靈魂裂片",
        "rarity": "史詩",
        "multiplier": 2.25,
        "cooldown": 3,
        "self_hp_cost": "4%",
        "sword_aura": None,
        "effect": "消耗自身最大 HP 4%，造成 MATK×225% 傷害；自身 MATK +15%，持續 2 回合。",
        "note": None
    },
    {
        "id": 89,
        "type": "魔法",
        "school": "自殘禁咒流",
        "name": "黑曜獻祭",
        "rarity": "傳說",
        "multiplier": 3,
        "cooldown": 4,
        "self_hp_cost": "5%",
        "sword_aura": None,
        "effect": "消耗自身最大 HP 5%，造成 MATK×300% 傷害；若 HP 低於 50%，附加 2 種 Debuff，持續 4 回合。",
        "note": None
    },
    {
        "id": 90,
        "type": "魔法",
        "school": "自殘禁咒流",
        "name": "終焉咒輪",
        "rarity": "神話",
        "multiplier": 4,
        "cooldown": 6,
        "self_hp_cost": "6%",
        "sword_aura": None,
        "effect": "消耗自身最大 HP 6%，造成 MATK×400% 傷害；HP 越低最高額外 +100%；敵人每有 1 個 Debuff 額外 +35%，最多 +175%。",
        "note": None
    },
    {
        "id": 91,
        "type": "魔法",
        "school": "特殊流",
        "name": "鏡像爆破",
        "rarity": "史詩",
        "multiplier": 2.05,
        "cooldown": 3,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "造成 MATK×205% 傷害；若自身有 Buff，額外造成 MATK×90% 傷害。",
        "note": None
    },
    {
        "id": 92,
        "type": "魔法",
        "school": "特殊流",
        "name": "虛空裂縫",
        "rarity": "史詩",
        "multiplier": 2.2,
        "cooldown": 3,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "造成 MATK×220% 傷害；敵人 DEF -10%、MATK -10%，持續 4 回合。",
        "note": None
    },
    {
        "id": 93,
        "type": "魔法",
        "school": "特殊流",
        "name": "聖光審判",
        "rarity": "史詩",
        "multiplier": 2.3,
        "cooldown": 3,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "造成 MATK×230% 傷害；對不死、惡魔、黑暗類敵人傷害 +30%。",
        "note": None
    },
    {
        "id": 94,
        "type": "魔法",
        "school": "特殊流",
        "name": "黑日禁咒",
        "rarity": "傳說",
        "multiplier": 3.4,
        "cooldown": 5,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "對全體敵人造成 MATK×340% 傷害；使用後自身 MATK -15%，持續 2 回合。",
        "note": None
    },
    {
        "id": 95,
        "type": "魔法",
        "school": "特殊流",
        "name": "星界審判",
        "rarity": "神話",
        "multiplier": 4.2,
        "cooldown": 6,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "造成 MATK×420% 傷害；敵人有 3 個以上 Debuff 時，倍率改為 540%。",
        "note": None
    },
    {
        "id": 96,
        "type": "Buff",
        "school": "通用Buff",
        "name": "戰吼",
        "rarity": "普通",
        "multiplier": None,
        "cooldown": 2,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "持續 2 回合。ATK +10%。",
        "note": None
    },
    {
        "id": 97,
        "type": "Buff",
        "school": "通用Buff",
        "name": "守備姿態",
        "rarity": "普通",
        "multiplier": None,
        "cooldown": 2,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "持續 2 回合。DEF +15%。",
        "note": None
    },
    {
        "id": 98,
        "type": "Buff",
        "school": "通用Buff",
        "name": "疾行",
        "rarity": "普通",
        "multiplier": None,
        "cooldown": 2,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "持續 2 回合。SPD +12%。",
        "note": None
    },
    {
        "id": 99,
        "type": "Buff",
        "school": "通用Buff",
        "name": "魔力集中",
        "rarity": "普通",
        "multiplier": None,
        "cooldown": 2,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "持續 2 回合。MATK +12%。",
        "note": None
    },
    {
        "id": 100,
        "type": "Buff",
        "school": "通用Buff",
        "name": "鷹眼",
        "rarity": "普通",
        "multiplier": None,
        "cooldown": 2,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "持續 2 回合。暴擊率 +10%，暴擊傷害 +15%。",
        "note": None
    },
    {
        "id": 101,
        "type": "Buff",
        "school": "進階Buff",
        "name": "鐵壁",
        "rarity": "稀有",
        "multiplier": None,
        "cooldown": 3,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "持續 2 回合。DEF +25%。",
        "note": None
    },
    {
        "id": 102,
        "type": "Buff",
        "school": "進階Buff",
        "name": "狂熱",
        "rarity": "稀有",
        "multiplier": None,
        "cooldown": 3,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "持續 2 回合。ATK +20%，但受到傷害 +10%。",
        "note": None
    },
    {
        "id": 103,
        "type": "Buff",
        "school": "進階Buff",
        "name": "獵殺標記",
        "rarity": "稀有",
        "multiplier": None,
        "cooldown": 3,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "持續 4 回合。指定敵人受到遠程傷害 +15%。",
        "note": None
    },
    {
        "id": 104,
        "type": "Buff",
        "school": "進階Buff",
        "name": "劍心",
        "rarity": "稀有",
        "multiplier": None,
        "cooldown": 4,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "持續 2 回合。使用近戰技能時額外獲得 1 層劍氣，每回合最多 1 次。",
        "note": None
    },
    {
        "id": 105,
        "type": "Buff",
        "school": "進階Buff",
        "name": "影流",
        "rarity": "稀有",
        "multiplier": None,
        "cooldown": 4,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "持續 2 回合。SPD +20%，刺殺流 SPD 傷害上限提高到 70%。",
        "note": None
    },
    {
        "id": 106,
        "type": "Buff",
        "school": "史詩Buff",
        "name": "王者號令",
        "rarity": "史詩",
        "multiplier": None,
        "cooldown": 4,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "持續 3 回合。ATK、RATK、MATK、DEF +12%。",
        "note": None
    },
    {
        "id": 107,
        "type": "Buff",
        "school": "史詩Buff",
        "name": "戰神祝福",
        "rarity": "史詩",
        "multiplier": None,
        "cooldown": 4,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "持續 2 回合。暴擊率 +20%，暴擊傷害 +25%。",
        "note": None
    },
    {
        "id": 108,
        "type": "Buff",
        "school": "史詩Buff",
        "name": "無我境界",
        "rarity": "史詩",
        "multiplier": None,
        "cooldown": 4,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "持續 1 回合。下一次技能傷害 +30%。",
        "note": None
    },
    {
        "id": 109,
        "type": "Buff",
        "school": "史詩Buff",
        "name": "血怒契約",
        "rarity": "史詩",
        "multiplier": None,
        "cooldown": 4,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "持續 3 回合。ATK +30%，每回合失去最大 HP 5%。",
        "note": None
    },
    {
        "id": 110,
        "type": "Buff",
        "school": "史詩Buff",
        "name": "魔紋增幅",
        "rarity": "史詩",
        "multiplier": None,
        "cooldown": 4,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "持續 2 回合。MATK +28%，DEF -10%。",
        "note": None
    },
    {
        "id": 111,
        "type": "Buff",
        "school": "史詩Buff",
        "name": "劍氣凝神",
        "rarity": "史詩",
        "multiplier": None,
        "cooldown": 4,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "持續 立即。立刻獲得 2 層劍氣。",
        "note": None
    },
    {
        "id": 112,
        "type": "Buff",
        "school": "傳說Buff",
        "name": "不動如山",
        "rarity": "傳說",
        "multiplier": None,
        "cooldown": 5,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "持續 2 回合。DEF +40%，免疫降速與不能行動效果。",
        "note": None
    },
    {
        "id": 113,
        "type": "Buff",
        "school": "傳說Buff",
        "name": "時間加速",
        "rarity": "傳說",
        "multiplier": None,
        "cooldown": 5,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "持續 2 回合。所有技能冷卻 -1，SPD +25%。",
        "note": None
    },
    {
        "id": 114,
        "type": "Buff",
        "school": "傳說Buff",
        "name": "死線瞄準",
        "rarity": "傳說",
        "multiplier": None,
        "cooldown": 5,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "持續 1 回合。下一個遠程技能傷害 +45%；若敵人有標記，額外 +25%。",
        "note": None
    },
    {
        "id": 115,
        "type": "Buff",
        "school": "傳說Buff",
        "name": "咒術展開",
        "rarity": "傳說",
        "multiplier": None,
        "cooldown": 5,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "持續 1 回合。下一個魔法技能傷害 +25%，並將造成的 Debuff 持續時間刷新為 4 回合。",
        "note": None
    },
    {
        "id": 116,
        "type": "Buff",
        "school": "傳說Buff",
        "name": "血戰姿態",
        "rarity": "傳說",
        "multiplier": None,
        "cooldown": 5,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "持續 2 回合。自身 HP 低於 50% 時，ATK、RATK、MATK +35%。",
        "note": None
    },
    {
        "id": 117,
        "type": "Buff",
        "school": "傳說Buff",
        "name": "血境覺醒",
        "rarity": "傳說",
        "multiplier": None,
        "cooldown": 5,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "持續 3 回合。根據已損血量提高 ATK、RATK、MATK。加成 B=(1-HP%)×136%。",
        "note": None
    },
    {
        "id": 118,
        "type": "Buff",
        "school": "神話Buff",
        "name": "不滅王座",
        "rarity": "神話",
        "multiplier": None,
        "cooldown": 6,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "持續 2 回合。獲得最大 HP 50% 的護盾，護盾存在時 DEF +30%。",
        "note": None
    },
    {
        "id": 119,
        "type": "Buff",
        "school": "神話Buff",
        "name": "修羅覺醒",
        "rarity": "神話",
        "multiplier": None,
        "cooldown": 6,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "持續 2 回合。ATK +45%，所有近戰技能冷卻 -1，每回合失去最大 HP 8%。",
        "note": None
    },
    {
        "id": 120,
        "type": "Buff",
        "school": "神話Buff",
        "name": "萬劍歸宗",
        "rarity": "神話",
        "multiplier": None,
        "cooldown": 6,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "持續 3 回合。劍氣上限 +2，立刻獲得 2 層劍氣。",
        "note": None
    },
    {
        "id": 121,
        "type": "Buff",
        "school": "神話Buff",
        "name": "星辰詠唱",
        "rarity": "神話",
        "multiplier": None,
        "cooldown": 6,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "持續 2 回合。魔法暴擊率 +20%，魔法暴擊傷害 +80%。",
        "note": None
    },
    {
        "id": 122,
        "type": "Buff",
        "school": "神話Buff",
        "name": "狩神姿態",
        "rarity": "神話",
        "multiplier": None,
        "cooldown": 6,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "持續 1 回合。下一個遠程最大生命值傷害技能的額外 HP 傷害提高 50%，但仍受 Boss 上限。",
        "note": None
    },
    {
        "id": 123,
        "type": "Buff",
        "school": "神話Buff",
        "name": "血王降臨",
        "rarity": "神話",
        "multiplier": None,
        "cooldown": 6,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "持續 2 回合。HP 越低，全傷害越高。加成 B=(1-HP%)×204%。自殘技能不會讓自己低於 1 HP。",
        "note": None
    }
]

ULTIMATE_SKILLS = [
    {
        "id": 201,
        "type": "Buff",
        "school": "戰士防禦流",
        "name": "王城降臨",
        "rarity": "秘密",
        "multiplier": None,
        "cooldown": 9,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "展開王城狀態 5 回合：受到傷害 -30%；每次受到攻擊獲得 1 層城壁；每層城壁讓下一個近戰技能額外加入 DEF×60% 作為攻擊力，最多 6 層；結束時若仍有城壁，自動觸發城崩反擊：DEF×0.8×城壁層數。",
        "note": "終極技能；Boss 素材製作取得。",
        "craft_only": True,
    },
    {
        "id": 202,
        "type": "Buff",
        "school": "自殘狂戰流",
        "name": "血量拍賣",
        "rarity": "秘密",
        "multiplier": None,
        "cooldown": 8,
        "self_hp_cost": "50%",
        "sword_aura": None,
        "effect": "自損 50% 最大 HP，技能傷害 +75%，持續 2 回合；2 回合內血量不會低於 1。",
        "note": "終極技能；Boss 素材製作取得。",
        "craft_only": True,
    },
    {
        "id": 203,
        "type": "Buff",
        "school": "刺殺SPD流",
        "name": "影子替身",
        "rarity": "秘密",
        "multiplier": None,
        "cooldown": 8,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "召喚影子替身 3 回合；替身會複製接下來使用的第一個刺殺技能，造成原技能 65% 傷害；若自身 SPD 高於敵人，複製傷害提高為 90%；替身攻擊後自身 DEF -25%，持續 3 回合。此技能釋放後玩家可以再行動一回合。",
        "note": "終極技能；Boss 素材製作取得。",
        "craft_only": True,
    },
    {
        "id": 204,
        "type": "Buff",
        "school": "武士劍氣流",
        "name": "光之太刀",
        "rarity": "秘密",
        "multiplier": None,
        "cooldown": 10,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "進入納刀狀態 3 回合：期間不能使用傷害技能，可以使用 Buff；每回合獲得 5 層劍氣；受到傷害 -30%；第三回合時獲得劍氣後自動釋放光之太刀，根據現有所有劍氣造成 500% + 160%×目前劍氣數量。",
        "note": "終極技能；Boss 素材製作取得。",
        "craft_only": True,
    },
    {
        "id": 205,
        "type": "Buff",
        "school": "基礎射手流",
        "name": "戰術換位",
        "rarity": "秘密",
        "multiplier": None,
        "cooldown": 8,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "立即重整遠程節奏：SPD +40%，所有遠程技能冷卻 -2；下一個遠程技能傷害 +25%；若下一個遠程技能擊敗敵人，所有遠程技能再冷卻 -1。本回合不造成直接傷害。",
        "note": "終極技能；Boss 素材製作取得。",
        "craft_only": True,
    },
    {
        "id": 206,
        "type": "Buff",
        "school": "自殘射擊流",
        "name": "血彈裝填",
        "rarity": "秘密",
        "multiplier": None,
        "cooldown": 8,
        "self_hp_cost": "25%",
        "sword_aura": None,
        "effect": "消耗最大 HP 25%，獲得 3 發血彈；接下來 3 個遠程技能各消耗 1 發血彈並追加 (ATK+RATK)×350% 傷害；若自身 HP 低於 40%，每發血彈追加傷害改為 (ATK+RATK)×330%；血彈最多存在 4 回合。",
        "note": "終極技能；Boss 素材製作取得。",
        "craft_only": True,
    },
    {
        "id": 207,
        "type": "遠程",
        "school": "破甲流",
        "name": "拆解協議",
        "rarity": "秘密",
        "multiplier": 2.6,
        "cooldown": 9,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "造成 (ATK+RATK)×260% 傷害並套用拆解 4 回合：裂甲上限 +3 層，套用 3 層裂甲 debuff；拆解狀態下，敵人每有 1 層裂甲，受到所有傷害 +20%；敵人獲得護盾時護盾值降低 50%；敵人 DEF Buff 無效；若敵人裂甲達 3 層，立刻額外觸發 (ATK+RATK)×180% 傷害。",
        "note": "終極技能；Boss 素材製作取得。",
        "craft_only": True,
    },
    {
        "id": 208,
        "type": "遠程",
        "school": "最大生命值傷害流",
        "name": "巨獸解剖",
        "rarity": "秘密",
        "multiplier": 1.8,
        "cooldown": 10,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "造成 (ATK+RATK)×180% 傷害並套用解剖紀錄：之後每次對該敵人造成遠程傷害，獲得 1 層解剖；每層解剖使最大生命值傷害技能額外 +1.2% 目標最大 HP；最多 6 層。",
        "note": "終極技能；Boss 素材製作取得。",
        "craft_only": True,
    },
    {
        "id": 209,
        "type": "Buff",
        "school": "標記/延遲流",
        "name": "命運倒數",
        "rarity": "秘密",
        "multiplier": None,
        "cooldown": 9,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "指定敵人獲得命運倒數 3 回合；期間敵人每受到一次遠程技能傷害，記錄該次傷害 70%；3 回合後將記錄傷害全部引爆；若敵人有標記，引爆傷害 +25%。",
        "note": "終極技能；Boss 素材製作取得。",
        "craft_only": True,
    },
    {
        "id": 210,
        "type": "魔法",
        "school": "Debuff流",
        "name": "惡咒轉生",
        "rarity": "秘密",
        "multiplier": 4.2,
        "cooldown": 9,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "造成 (ATK+MATK)×420% 傷害並觸發惡咒轉生：敵人每有 1 個 Debuff，立刻觸發 1 次詛咒脈衝；每次脈衝造成 (ATK+MATK)×160% 傷害；不移除 Debuff；最多 6 次；若觸發 4 次以上，刷新所有 Debuff 到 4 回合。",
        "note": "終極技能；Boss 素材製作取得。",
        "craft_only": True,
    },
    {
        "id": 211,
        "type": "魔法",
        "school": "控場流",
        "name": "回合竊取",
        "rarity": "秘密",
        "multiplier": 3.8,
        "cooldown": 10,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "造成 (ATK+MATK)×380% 傷害並竊取節奏：一般敵人下一回合不能行動；自己獲得竊取回合狀態，使下一個技能冷卻不增加；若目標是 Boss，敵人下一次傷害 -35%。",
        "note": "終極技能；Boss 素材製作取得。",
        "craft_only": True,
    },
    {
        "id": 212,
        "type": "Buff",
        "school": "暴擊傷害流",
        "name": "星圖重寫",
        "rarity": "秘密",
        "multiplier": None,
        "cooldown": 9,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "進入星圖重寫 4 回合：每一回合累積 1 層星痕；每層星痕使下一次魔法暴擊傷害 +60%；最多 4 層；一旦魔法暴擊就額外加 1 層星痕。",
        "note": "終極技能；Boss 素材製作取得。",
        "craft_only": True,
    },
    {
        "id": 213,
        "type": "Buff",
        "school": "通用爆發",
        "name": "最後命令",
        "rarity": "秘密",
        "multiplier": None,
        "cooldown": 10,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "下一個技能傷害 +100%；若沒有擊敗敵人，自己受到最大 HP 15% 的反噬傷害。",
        "note": "終極技能；Boss 素材製作取得。",
        "craft_only": True,
    },
    {
        "id": 214,
        "type": "Buff",
        "school": "通用反擊",
        "name": "因果倒轉",
        "rarity": "秘密",
        "multiplier": None,
        "cooldown": 9,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "需要上一回合受傷。記錄上一回合自己受到的傷害；下一個技能額外造成「(記錄傷害+ATK+DEF)×150%」的固定傷害。",
        "note": "終極技能；Boss 素材製作取得。",
        "craft_only": True,
    },
    {
        "id": 215,
        "type": "Buff",
        "school": "通用蓄力",
        "name": "空白回合",
        "rarity": "秘密",
        "multiplier": None,
        "cooldown": 8,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "本回合不造成傷害；下一回合技能傷害 +80%、所有技能冷卻 -1，並獲得受到傷害 -20% 效果 1 回合。",
        "note": "終極技能；Boss 素材製作取得。",
        "craft_only": True,
    },
    {
        "id": 216,
        "type": "Buff",
        "school": "通用禁忌",
        "name": "禁忌開關",
        "rarity": "秘密",
        "multiplier": None,
        "cooldown": 12,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "開啟禁忌模式 3 回合：每一回合所有技能冷卻額外 -1；技能傷害 +35%；Buff 效果 +30%；結束後自身 DEF -30%，持續 2 回合。",
        "note": "終極技能；Boss 素材製作取得。",
        "craft_only": True,
    },
    {
        "id": 217,
        "type": "Buff",
        "school": "戰場規則",
        "name": "世界裂縫",
        "rarity": "秘密",
        "multiplier": None,
        "cooldown": 12,
        "self_hp_cost": None,
        "sword_aura": None,
        "effect": "開啟世界裂縫 4 回合：所有角色造成傷害 +45%；所有 Debuff 持續時間 +1；所有護盾效果 -30%；所有自殘技能額外自損 +2hp%；每回合結束時雙方受到最大 HP 3% 的裂縫傷害。",
        "note": "終極技能；Boss 素材製作取得。",
        "craft_only": True,
    },
]

SKILLS.extend(ULTIMATE_SKILLS)

_SKILL_OVERRIDES = {
    1: {
        "name": "盾鋒斬",
        "rarity": "普通",
        "multiplier": 1.0,
        "cooldown": 0,
        "effect": "將 DEF×25% 加入本次傷害；若自己已有護盾，額外獲得本次傷害 8% 的護盾，持續 2 回合。",
    },
    2: {
        "name": "鐵壁重擊",
        "rarity": "普通",
        "multiplier": 1.1,
        "cooldown": 1,
        "effect": "將 DEF×35% 加入本次傷害；使用後自身 DEF +10%，持續 2 回合。",
    },
    3: {
        "name": "守勢反打",
        "rarity": "普通",
        "multiplier": 0.95,
        "cooldown": 1,
        "effect": "將 DEF×45% 加入本次傷害；若上一回合受到傷害，本次倍率額外 +30%。",
    },
    4: {
        "name": "碎盾壓制",
        "rarity": "稀有",
        "multiplier": 1.35,
        "cooldown": 2,
        "effect": "將 DEF×60% 加入本次傷害；使敵人 DEF -12%，持續 3 回合。",
    },
    5: {
        "name": "堡壘突進",
        "rarity": "稀有",
        "multiplier": 1.45,
        "cooldown": 2,
        "effect": "將 DEF×70% 加入本次傷害；獲得本次傷害 8% 的護盾，持續 2 回合。",
    },
    6: {
        "name": "鋼魂震擊",
        "rarity": "史詩",
        "multiplier": 1.65,
        "cooldown": 3,
        "effect": "將 DEF×85% 加入本次傷害；自身 DEF 每有 100 點，額外獲得 1% 傷害減免，最高 20%，持續 2 回合。",
    },
    7: {
        "name": "不動斷岳",
        "rarity": "史詩",
        "multiplier": 1.8,
        "cooldown": 3,
        "effect": "將 DEF×95% 加入本次傷害；若自身 DEF 高於 ATK，額外 +45% 倍率。",
    },
    8: {
        "name": "聖盾裁決",
        "rarity": "傳說",
        "multiplier": 2.15,
        "cooldown": 4,
        "effect": "將 DEF×110% 加入本次傷害；本次傷害的 15% 轉化為護盾，持續 2 回合。",
    },
    9: {
        "name": "王城鎮壓",
        "rarity": "傳說",
        "multiplier": 2.3,
        "cooldown": 4,
        "effect": "將 DEF×120% 加入本次傷害；若自身有護盾，額外 +60% 倍率，並刷新自身 DEF 增益 1 回合。",
    },
    10: {
        "name": "神壁天罰",
        "rarity": "神話",
        "multiplier": 2.7,
        "cooldown": 6,
        "effect": "將 DEF×130% 加入本次傷害；若自身有護盾，額外 +90% 倍率；命中後獲得本次傷害 15% 的護盾，持續 2 回合。",
    },
    14: {
        "effect": "消耗自身最大 HP 10%，造成 ATK×310% 傷害；自身 HP 低於 50% 時，技能倍率變為 1.8 到 2.3 倍。",
    },
    15: {
        "effect": "消耗自身最大 HP 12%，造成 ATK×430% 傷害；自身 HP 低於 50% 時，技能倍率變為 1.8 到 2.3 倍。",
    },
    45: {
        "effect": "消耗自身最大 HP 6%，造成 RATK×320% 傷害；若敵人有標記，額外 +70% 倍率；HP 低於 50% 時，技能倍率變為 1.8 到 2.3 倍。",
    },
    46: {
        "effect": "消耗自身最大 HP 7%，造成 RATK×410% 傷害；下一回合自動追加 RATK×80% 傷害；HP 低於 50% 時，技能倍率變為 1.8 到 2.3 倍。",
    },
    120: {
        "effect": "持續 3 回合。立刻獲得 4 層劍氣。",
    },
    31: {
        "name": "天照一閃",
        "rarity": "神話",
        "multiplier": 3,
        "cooldown": 7,
        "sword_aura": "全消耗",
        "effect": "以 (ATK+近戰) 計算。先獲得1層劍氣後，消耗全部劍氣。最終倍率 = 300% + 175%×消耗劍氣層數。",
    },
    30: {
        "name": "無明三段",
        "rarity": "傳說",
        "multiplier": 2.4,
        "cooldown": 4,
        "sword_aura": "-5",
        "effect": "以 (ATK+近戰) 計算。消耗5層劍氣。最終倍率 = 240%+175%×消耗劍氣層數，並且所有技能冷卻-1。",
    },
    53: {
        "effect": "造成 RATK×150% 傷害，額外造成目標最大 HP 1.5% 傷害；Boss 額外傷害上限 = (ATK+RATK)×60%。",
    },
    54: {
        "effect": "造成 RATK×205% 傷害，額外造成目標最大 HP 2.5% 傷害；Boss 額外傷害上限 = (ATK+RATK)×100%。",
    },
    55: {
        "effect": "造成 RATK×195% 傷害，額外造成目標最大 HP 2% 傷害，並給予巨獸標記 4 回合。",
    },
    56: {
        "effect": "造成 RATK×300% 傷害，額外造成目標最大 HP 4% 傷害；Boss 額外傷害上限 = (ATK+RATK)×180%。",
    },
    57: {
        "effect": "造成 RATK×390% 傷害，額外造成目標最大 HP 8% 傷害；若有巨獸標記，改為 10%；Boss 額外傷害上限 = (ATK+RATK)×350%。",
    },
    80: {
        "effect": "下一次魔法暴擊傷害 +50%，持續 2 回合。",
    },
    81: {
        "effect": "附加魔紋刻印，敵人受到的魔法暴擊傷害 +45%，持續 4 回合。",
    },
    82: {
        "effect": "若本次暴擊，額外造成 210% 倍率可暴擊傷害。",
    },
    83: {
        "effect": "自身魔法暴擊傷害 +55%，持續 2 回合。",
    },
    84: {
        "effect": "若敵人有魔紋刻印，額外 +80% 總傷害。",
    },
    85: {
        "effect": "若本次暴擊，技能傷害增加40%後額外造成一次可暴擊的410%倍率傷害，技能傷害buff持續3回合。",
    },
    63: {
        "name": "魔彈",
        "rarity": "普通",
        "multiplier": 0.9,
        "cooldown": 0,
        "effect": "沒有額外效果。",
    },
    64: {
        "name": "火球術",
        "rarity": "普通",
        "multiplier": 1.2,
        "cooldown": 0,
        "effect": "附加灼燒：每回合 (ATK+MATK)×10% 傷害，持續 4 回合。",
    },
    65: {
        "name": "冰錐術",
        "rarity": "普通",
        "multiplier": 1.15,
        "cooldown": 1,
        "effect": "敵人 SPD -10%，持續 4 回合。",
    },
    66: {
        "name": "雷擊",
        "rarity": "普通",
        "multiplier": 1.3,
        "cooldown": 1,
        "effect": "本次暴擊率 +10%。",
    },
    67: {
        "name": "毒霧",
        "rarity": "稀有",
        "multiplier": 1.1,
        "cooldown": 2,
        "effect": "對全體敵人附加中毒：每回合 (ATK+MATK)×20% 傷害，持續 4 回合。",
    },
    68: {
        "name": "炎爆術",
        "rarity": "稀有",
        "multiplier": 1.65,
        "cooldown": 2,
        "effect": "附加燃燒：每回合 (ATK+MATK)×30% 傷害，持續 4 回合。",
    },
    69: {
        "name": "岩槍術",
        "rarity": "稀有",
        "multiplier": 1.7,
        "cooldown": 2,
        "effect": "敵人 DEF -15%，持續 4 回合。",
    },
    70: {
        "name": "暗影球",
        "rarity": "稀有",
        "multiplier": 1.6,
        "cooldown": 2,
        "effect": "回復本次造成傷害的 8% HP。",
    },
    71: {
        "name": "流星雨",
        "rarity": "史詩",
        "multiplier": 2.3,
        "cooldown": 3,
        "effect": "對全體敵人造成傷害。",
    },
    72: {
        "name": "深淵爆裂",
        "rarity": "史詩",
        "multiplier": 2.4,
        "cooldown": 3,
        "effect": "附加黑火：每回合 (ATK+MATK)×35% 傷害，持續 3 回合。",
    },
    73: {
        "name": "極寒末日",
        "rarity": "傳說",
        "multiplier": 3.1,
        "cooldown": 4,
        "effect": "對全體敵人造成傷害，敵人 SPD -25%，持續 4 回合。",
    },
    74: {
        "name": "混沌星核",
        "rarity": "神話",
        "multiplier": 4.3,
        "cooldown": 6,
        "effect": "如果敵人身上有中毒、燃燒、灼燒、黑火持續傷害技能，立即結算所有傷害並移除debuff。",
    },
}

_DAMAGE_BASE_BY_TYPE = {
    "近戰": "(ATK+近戰)",
    "遠程": "(ATK+RATK)",
    "魔法": "(ATK+MATK)",
}
_SCHOOL_MULTIPLIER_SCALE = {
    "控場流": 1.8,
    "基礎射手流": 1.6,
}


def _multiplier_percent(value: object) -> str:
    percent = float(value or 1) * 100
    return str(int(round(percent))) if abs(percent - round(percent)) < 0.01 else f"{percent:.1f}"


def _replace_standalone_damage_bases(effect: str, base: str) -> str:
    for token in ("ATK", "RATK", "MATK"):
        effect = re.sub(rf"(?<![\w+)]){token}×", f"{base}×", effect)
    return effect


def _scale_school_multiplier(skill: dict) -> None:
    if skill.get("craft_only"):
        return
    scale = _SCHOOL_MULTIPLIER_SCALE.get(skill.get("school"))
    if not scale or skill.get("multiplier") is None:
        return
    skill["multiplier"] = round(float(skill["multiplier"]) * scale, 4)


def _update_assassination_effect(skill: dict) -> None:
    if skill.get("school") != "刺殺流":
        return
    effect = str(skill.get("effect") or "")
    effect = effect.replace("額外根據 SPD 增傷：min(SPD×0.2%, 60%)", "額外造成 (ATK+近戰)×SPD×0.4% 傷害")
    effect = effect.replace("額外根據 SPD 增傷", "額外造成 (ATK+近戰)×SPD×0.4% 傷害")
    effect = effect.replace("給敵人 1 層影痕，最多 3 層，持續 4 回合", "給敵人 2 層影痕，持續 4 回合")
    if "給敵人 2 層影痕" not in effect:
        effect = effect.rstrip("。") + "；命中後附加 1 層影痕，持續 4 回合。"
    if "影痕每層使目標受到傷害 +8%" not in effect:
        effect = effect.rstrip("。") + "；影痕每層使目標受到傷害 +8%。"
    skill["effect"] = effect


def _normalize_skill_effect(skill: dict) -> None:
    if skill.get("type") == "Buff":
        return
    base = _DAMAGE_BASE_BY_TYPE.get(skill.get("type"))
    if not base:
        return

    effect = str(skill.get("effect") or "沒有額外效果。")
    effect = _replace_standalone_damage_bases(effect, base)
    formula = f"{base}×{_multiplier_percent(skill.get('multiplier'))}%"

    if "最終倍率" not in effect:
        effect = re.sub(
            rf"{re.escape(base)}×\d+(?:\.\d+)?%",
            formula,
            effect,
            count=1,
        )
        if not re.search(r"(?:造成|對全體敵人造成)\s*\(", effect):
            prefix = f"對全體敵人造成 {formula} 傷害" if effect.startswith("對全體敵人") else f"造成 {formula} 傷害"
            if effect in {"沒有額外效果。", "無效果"}:
                effect = prefix + "。沒有額外效果。"
            elif effect.startswith("對全體敵人造成傷害"):
                effect = effect.replace("對全體敵人造成傷害", prefix, 1)
            elif effect.startswith("對全體敵人附加"):
                effect = prefix + "，並" + effect
            elif effect.startswith(("附加", "敵人", "本次", "回復", "如果")):
                effect = prefix + "，" + effect
            elif not effect.startswith(("造成", "對全體敵人造成", "消耗自身最大 HP")):
                effect = prefix + "；" + effect

    skill["effect"] = effect


for _skill in SKILLS:
    if _skill["id"] in _SKILL_OVERRIDES:
        _skill.update(_SKILL_OVERRIDES[_skill["id"]])
    _scale_school_multiplier(_skill)
    _update_assassination_effect(_skill)
    _normalize_skill_effect(_skill)

SKILLS_BY_ID = {skill["id"]: skill for skill in SKILLS}
